runtime: python39

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "service-account-key.json"

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto

timeout: 60s
